pipeline {
    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {
        stage('Update Packages') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y libpq-dev python3 python3-pip python3-venv'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    python -m pip install --upgrade pip
                    python -m pip install -r "PyTest DQ Framework/requirements.txt"
                '''
            }
        }

        stage('Run PyTest DQ Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    cd "PyTest DQ Framework/tests"
                    export PYTHONPATH="$WORKSPACE/PyTest DQ Framework"

                    python -m pytest dq_checks/parquet_files \
                      --db_host=host.containers.internal \
                      --db_port=5434 \
                      --db_name=mydatabase \
                      --db_user=$POSTGRES_SECRET_USR \
                      --db_password=$POSTGRES_SECRET_PSW \
                      --html=../report.html \
                      --self-contained-html
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
            archiveArtifacts artifacts: 'PyTest DQ Framework/report.html', allowEmptyArchive: true
        }
        success {
            echo 'PyTest DQ pipeline executed successfully!'
        }
        failure {
            echo 'PyTest DQ pipeline failed. Please check the logs for details.'
        }
    }
}
