[pytest]
markers =
    validate_csv: tests for CSV validation
    unmarked: tests without explicit marks

python_files = test_*.py

addopts = --html=report.html --self-contained-html --reportportal


rp_endpoint = https://reportportal.epam.com/api/v1
rp_project = aliaksei_darashenka_personal
rp_api_key = my-api-key
rp_launch = PyTest Homework Launch
rp_log_batch_size = 20
